services:
  proxy:
    build:
      context: ../..
      dockerfile: ./docker/devcontainer/Dockerfile
    command: sleep infinity
    network_mode: host
    container_name: devcontainer-proxy
  # Use the same image as the devcontainer for consistency
    platform: linux/amd64
    volumes:
      - ../../..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    group_add:
      - docker
