global:
     scrape_interval: 15s
   scrape_configs:
     - job_name: "prometheus"
       static_configs:
         - targets: ["localhost:9090"]

# global:
#   scrape_interval: 15s
#   evaluation_interval: 15s
#   scrape_timeout: 10s

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# rule_files:
#   - "/etc/prometheus/rules/*.yml"

# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['localhost:9090']

#   - job_name: 'alertmanager'
#     static_configs:
#       - targets: ['alertmanager:9093']

#   - job_name: 'node-exporter'
#     static_configs:
#       - targets: ['node-exporter:9100']

#   - job_name: 'cadvisor'
#     static_configs:
#       - targets: ['cadvisor:8080']

#   - job_name: 'traefik'
#     static_configs:
#       - targets: ['traefik:8080']

#   - job_name: 'consul'
#     static_configs:
#       - targets: ['consul:8500']
#     metrics_path: '/v1/agent/metrics'
#     scheme: 'http' 