# Certificate Configuration
# This file defines all certificates to be generated and their bundles

# Global defaults that can be overridden by individual certificates
defaults:
  common_name: "traefik"  # Can be overridden by CLI --common-name or env COMMON_NAME
  hosts: "localhost,127.0.0.1,traefik"  # Can be overridden by CLI --hosts or env HOSTS
  domain: "example.com"  # Can be overridden by CLI --domain or env DOMAIN
  profile: "server"
  permissions:
    mode: 0o644  # File permissions (octal)
    owner: "traefik"  # File owner
    group: "traefik"  # File group

# CA Configuration
ca:
  generate: true  # Set to false to use existing CA
  name: "ca"
  common_name: "FinancialPayments CA"
  hosts: "localhost,127.0.0.1"
  domain: "example.com"
  # No permissions specified - no changes made to file permissions

# Individual Certificates
certificates:
  # Example 1: No permissions specified - no changes made
  - name: "wildcard_herringbank"
    type: "server"
