global:
  resolve_timeout: 5m
  # Uncomment and configure these if you want to use email notifications
  # smtp_smarthost: 'smtp.gmail.com:587'
  # smtp_from: 'alertmanager@yourdomain.com'
  # smtp_auth_username: 'your-email@gmail.com'
  # smtp_auth_password: 'your-app-specific-password'
  # smtp_require_tls: true

# Uncomment and configure this if you want to use Slack notifications
# slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

route:
  group_by: ['alertname', 'job', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-receiver'
      continue: true
    - match:
        severity: warning
      receiver: 'warning-receiver'
      continue: true

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'alerts@yourdomain.com'
        send_resolved: true
    # Uncomment to enable Slack notifications
    # slack_configs:
    #   - channel: '#alerts'
    #     send_resolved: true
    #     title: '{{ template "slack.default.title" . }}'
    #     text: '{{ template "slack.default.text" . }}'

  - name: 'critical-receiver'
    email_configs:
      - to: 'critical-alerts@yourdomain.com'
        send_resolved: true
    # Uncomment to enable Slack notifications
    # slack_configs:
    #   - channel: '#critical-alerts'
    #     send_resolved: true
    #     title: '{{ template "slack.default.title" . }}'
    #     text: '{{ template "slack.default.text" . }}'

  - name: 'warning-receiver'
    email_configs:
      - to: 'warnings@yourdomain.com'
        send_resolved: true
    # Uncomment to enable Slack notifications
    # slack_configs:
    #   - channel: '#warning-alerts'
    #     send_resolved: true
    #     title: '{{ template "slack.default.title" . }}'
    #     text: '{{ template "slack.default.text" . }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl' 