name: Build and Release

on:
  push:
    branches: [main, develop]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug - List files
        run: |
          pwd
          ls -la
          ls -la scripts/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcrypt-dev

      - name: Make build script executable
        run: |
          ls -la scripts/build_all.sh
          chmod +x scripts/build_all.sh
          ls -la scripts/build_all.sh

      - name: Build binaries
        run: ./scripts/build_all.sh

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: releases/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: ./releases

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ steps.get_version.outputs.VERSION }}
          body: |
            ## What's Changed
            
            This release includes binaries for multiple platforms:
            - Linux (AMD64, ARM64)
            - macOS (AMD64, ARM64)
            - Windows (AMD64)
            
            ## Binaries
            
            The following binaries are available for download:
            ${{ join(matrix.asset_name, '\n') }}
          files: ./releases/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
